stages:
  - PullImages
  - KK
before_script:
  - tag=` date +%Y%m%d%H%M%S`
  - echo $tag
PullImages:
  stage: PullImages
  script:
    - pwd
    
#KK:
#    stage: KK
#    scripts:
#     - id
#     -date 
#    when: on_failure
    - make gman
    - cp ./build/bin/gman /home/public/dailybuild/go-matrix/gman$tag
#    - ssh 192.168.3.99 "docker  build -t ptone.jp/wallet:v4 . ;docker push  ptone.jp/wallet"
#    - make
#    - cp ./build/bin/geth /home/public/geth_backup/2geth$tag
#    - docker tag  "registry.gitlab.com/ptminddev/website/datadeck-site/master/datadeck-site-com" "registry.gitlab.com/ptminddev/website/datadeck-site/master/datadeck-site-com:${tag}"
#    - docker push "registry.gitlab.com/ptminddev/website/datadeck-site/master/datadeck-site-com:${tag}"
#    - rancher --url http://192.168.3.60:8080/v1/projects/1a79 --access-key '7F741675D3D094A6A7E8' --secret-key 'WTdi6FbCP7nrQqmb6SLxPGt88ajbm5ukfZM1Aznp5' export kubernetes-ingress-lbs && cd kubernetes-ingress-lbs
#    - rancher-compose --url http://192.168.3.60:8080/v1/projects/1a79 --access-key '7F741675D3D094A6A7E8' --secret-key 'WTdi6FbCP7nrQqmb6SLxPGt88ajbm5ukfZM1Aznp' up -d -c --force-upgrade aaa
  only:
    - master
